---
title: "R Markdown"
subtitle: "E-books Only"
editor: 
  markdown: 
    wrap: 60
---

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/JoscelinRocha">![Buy
me a
coffee](https://cdn.buymeacoffee.com/buttons/bmc-new-btn-logo.svg){alt="Buy me a coffee"
width="15" height="21"}Buy me a coffee</a>

------------------------------------------------------------

## [Bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)

By [Yihui Xie](https://bookdown.org/yihui/bookdown/)

**What is this?**

**Excerpt from ebook:** This short book introduces an R
package, bookdown, to change your workflow of writing books.
It should be technically easy to write a book, visually
pleasant to view the book, fun to interact with the book,
convenient to navigate through the book, straightforward for
readers to contribute or leave feedback to the book
author(s), and more importantly, authors should not always
be distracted by typesetting details.

1.  Link to ebook here:
    <https://bookdown.org/yihui/bookdown/>
2.  Link to buy book here: [CRC
    Press](https://www.routledge.com/bookdown-Authoring-Books-and-Technical-Documents-with-R-Markdown/Xie/p/book/9781138700109?utm_source=crcpress.com&utm_medium=referral)

## [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)💯 💯

By [Yihui Xie, Christophe Dervieux, Emily
Riederer](https://bookdown.org/yihui/rmarkdown-cookbook/)

**What is this?**

**Excerpt from ebook:** This book aims to draw together
popular posts from Stack Overflow and other online resources
(such as blog posts or tutorials) to provide up-to-date
solutions for everyday queries that users commonly make. In
fact, to help us make decisions on the potential topics to
cover in this book, the second author of this book,
Christophe, has built an R Markdown dashboard to scrape
Stack Overflow daily for the most popular posts. Hopefully,
our cookbook can become more useful by including recipes
from these popular posts.

1.  Link to ebook here:
    <https://bookdown.org/yihui/rmarkdown-cookbook/>

## [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/#)💯 💯

By [Yihui Xie, J. J. Allaire, & Garrett
Grolemund](https://bookdown.org/yihui/rmarkdown/#)

**What is this?**\
**Excerpt from ebook:** Note that this book is intended to
be a guide instead of the comprehensive documentation of all
topics related to R Markdown. Some chapters are only
overviews, and you may need to consult the full
documentation elsewhere (often freely available online)

1.  Link to ebook here:
    <https://bookdown.org/yihui/rmarkdown/#>

## [R Markdown for Scientists](https://rmd4sci.njtierney.com/)

By [Nicholas Tierney](https://rmd4sci.njtierney.com/)

**What is this?**

**Excerpt from site:** This is a book on rmarkdown, aimed
for scientists. It was initially developed as a 3 hour
workshop, but is now developed into a resource that will
grow and change over time as a living book.

1.  Link to web-book here: <https://rmd4sci.njtierney.com/>
