---
title: "Making Websites & Blogs"
editor: 
  markdown: 
    wrap: 72
---

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/JoscelinRocha">![Buy
me a
coffee](https://cdn.buymeacoffee.com/buttons/bmc-new-btn-logo.svg){alt="Buy me a coffee"
width="15" height="21"}Buy me a coffee</a>

------------------------------------------------------------------------

## [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/)

By [by Yihui Xie, Amber Thomas, & Alison Presmanes
Hill](https://bookdown.org/yihui/blogdown/)

**What is this?**\
**Excerpt from ebook:** We introduce an R package, blogdown, in this
short book, to teach you how to create websites using R Markdown and
Hugo. If you have experience with creating websites, you may naturally
ask what the benefits of using R Markdown are, and how blogdown is
different from existing popular website platforms, such as WordPress.

1.  Link to ebook here: <https://bookdown.org/yihui/blogdown/>

## [Creating a blog with Quarto in 10 steps](https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/)

By [Beatriz
Milz](https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/)

Added Sun April 30th 2023

**What is this?**

**Excerpt from blog:** I\'m going to write about some of the steps that
you need to take to create a blog with Quarto.

1.  Link to blog here:
    <https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/>

## [How to make your own website for free in under an hour](https://www.dsquintana.blog/create-an-academic-website-free-easy-2020/)

By
[Quintana](https://www.dsquintana.blog/create-an-academic-website-free-easy-2020/)
💯

**What is this?**

**Excerpt from blog:** This tutorial will walk you through how to make
your own website for free using the blogdown package in RStudio.

1.  Link to blog here(2019):
    <https://www.dsquintana.blog/free-website-in-r-easy/>
2.  Updated blog here (2020):
    <https://www.dsquintana.blog/create-an-academic-website-free-easy-2020/>
3.  Link to video here: <https://www.youtube.com/watch?v=ox_Ue9yzf-0>

## [How to build your personal academic website using opensource software](https://osf.io/jdv4n/)

By [Lena V. Kremin](https://osf.io/jdv4n/) 💯

**What is this?**

**Excerpt from site:** By following this workshop, you will go through
the first steps of setting up your own academic website. Your finished
website will contain your biography, photo, CV, contact information, and
recent publications.

1.  Link to materials here: <https://osf.io/jdv4n/>

## [Making shareable documents with Quarto](https://openscapes.github.io/quarto-website-tutorial/)

By
[Openscapes](https://openscapes.github.io/quarto-website-tutorial/#about)

Added Sun April 30th 2023

**What is this?**

**Excerpt from blog:** This is a 1-hour tutorial that can be used to
teach or as self-paced learning.

We introduce Quarto by exploring this tutorial website, and practicing
the basic Quarto workflow using different tools (GitHub browser,
RStudio, and Jupyter) for editing your website.

We\'ll start off from the browser so you don\'t need to install any
additional software, however this approach is very limited and you will
soon outgrow its capabilities. If you don\'t already have a workflow to
edit files and sync to GitHub from your computer, I recommend RStudio.
You don\'t need to know R to use RStudio, and it has powerful editor
features that make for happy workflows.

1.  Link to blog here:
    <https://openscapes.github.io/quarto-website-tutorial/>

## [Mastering Shiny](https://mastering-shiny.org/)

By [Hadley Wickham](https://mastering-shiny.org/)

**What is this?**\
**Excerpt from ebook:** This book complements Shiny's online
documentation and is intended to help app authors develop a deeper
understanding of Shiny. After reading this book, you'll be able to write
apps that have more customized UI, more maintainable code, and better
performance and scalability.

1.  Link to web-book here: <https://mastering-shiny.org/>

## [PrettyDoc Package](https://prettydoc.statr.me/)

Added Fri Oct 8th 2021

**What is this?**

**Excerpt from site:** The prettydoc package provides an alternative
engine, html_pretty, to knit your R Markdown document into pretty HTML
pages. Its usage is extremely easy: simply replace the
rmarkdown::html_document or rmarkdown::html_vignette output engine by
prettydoc::html_pretty in your R Markdown header, and use one of the
built-in themes and syntax highlighters.

1.  Link to site here: <https://prettydoc.statr.me/>

## [The ultimate guide to starting a Quarto blog](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html)

By [Albert
Rapp](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html)

Added Sun April 30th 2023

**What is this?**

**Excerpt from blog:** Today, I want to show you how to build a blog
with Quarto. This in-depth guide is the result of hours of working with
Quarto\'s amazingly detailed
[documentation](https://quarto.org/docs/reference/). Hopefully, it will
save you a lot of time and helps you start your own blog. Here\'s what
we will cover:

1.  Link to blog here:
    <https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html>

## [Using GitHub Actions to Build your Hugo Website](https://drmowinckels.io/blog/2021-03-23-using-github-actions-to-build-your-hugo-website/)

Added Sun June 6th 2021

**What is this?**

**Excerpt from blog:** What we want is Github Actions to run certain
operations on a set schedule, build our website with hugo, and then
trigger a Netlify deployment. In particular, we want to render the
content/about.Rmd and knit my CV which is located in
content/about/resume/am_mowinckel_cv.Rmd, and not commit these to git,
just have them rendered right before Hugo build

1.  Link to blog here:
    <https://drmowinckels.io/blog/2021-03-23-using-github-actions-to-build-your-hugo-website/>
