---
title: "R Markdown"
editor: 
  markdown: 
    wrap: 60
---

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/JoscelinRocha">![Buy
me a
coffee](https://cdn.buymeacoffee.com/buttons/bmc-new-btn-logo.svg){alt="Buy me a coffee"
width="15" height="21"}Buy me a coffee</a>

------------------------------------------------------------

## [An introduction to R-Markdown](https://apreshill.github.io/rmd4cdc/#1)

By [Dr. Alison Hill](https://apreshill.github.io/rmd4cdc/#1)

**What is this?**\
Slides giving an introduction to R-Markdown

1.  Link to slides: <https://apreshill.github.io/rmd4cdc/#1>

## [Bookdown: Authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)

By [Yihui Xie](https://bookdown.org/yihui/bookdown/)

**What is this?**

**Excerpt from ebook:** This short book introduces an R
package, bookdown, to change your workflow of writing books.
It should be technically easy to write a book, visually
pleasant to view the book, fun to interact with the book,
convenient to navigate through the book, straightforward for
readers to contribute or leave feedback to the book
author(s), and more importantly, authors should not always
be distracted by typesetting details.

1.  Link to ebook here:
    <https://bookdown.org/yihui/bookdown/>
2.  Link to buy book here: [CRC
    Press](https://www.routledge.com/bookdown-Authoring-Books-and-Technical-Documents-with-R-Markdown/Xie/p/book/9781138700109?utm_source=crcpress.com&utm_medium=referral)

## [Extending R Markdown](https://meghan.rbind.io/talk/rstudio/)

By [Meghan Hall](https://meghan.rbind.io/talk/rstudio/)

Added Sat Dec, 11, 2021

**What is it?**

**Excerpt from site:** "R Markdown is a powerful yet
underutilized tool for a powerful yet underutilized
component of data science---communicating your work. R
Markdown works seamlessly with other analytic work in R and
knowing the basics allows you to extend that knowledge into
producing PDFs, slides, websites, and more".

1.  Link to blog here:
    <https://meghan.rbind.io/talk/rstudio/>
2.  Link to slides here:
    <https://meghan.rbind.io/slides/RStudio/Hall_RStudio_2021.html#1>
3.  Link to video here:
    <https://community.rstudio.com/t/recording-of-r-in-sports-analytics-rstudio-enterprise-community-meetup/107551>
4.  Link to Github repo and code:
    <https://github.com/meghall06/personal-website/blob/master/static/slides/RStudio/Hall_RStudio_2021.Rmd>

## [grateful: Facilitate citation of R packages](https://pakillo.github.io/grateful/) 💯

By [Francisco Rodriguez-Sanchez & Connor P.
Jackson](https://pakillo.github.io/grateful/)

Added Mon Apr 24th, 2023

**What is it?**\
**Excerpt from package:** The goal of grateful is to make it
very easy to cite R and the R packages used in any analyses,
so that package authors receive their deserved credit. By
calling a single function, grateful will scan the project
for R packages used and generate a BibTeX file containing
all citations for those packages.

grateful can then generate a new document with citations in
the desired output format (Word, PDF, HTML, Markdown). These
references can be formatted for a specific journal, so that
we can just paste them directly into our manuscript or
report.

1.  Link to package: <https://pakillo.github.io/grateful/>

## [How I Teach R Markdown](https://alison.rbind.io/post/2020-05-28-how-i-teach-r-markdown/) 💯

By [Alison
Hill](https://alison.rbind.io/post/2020-05-28-how-i-teach-r-markdown/)

**What is it?**\
**Excerpt from blog:** So without further ado, here are some
of my guiding principles when introducing R Markdown to
beginners, for those who are ready to go beyond casual
knitter:

1.  Link to blog:
    <https://alison.rbind.io/post/2020-05-28-how-i-teach-r-markdown/>

## [Meta RMarkdown - Taxonomy and Use cases](https://themockup.blog/posts/2020-07-25-meta-rmarkdown/)

By [Thomas
Mock](https://themockup.blog/posts/2020-07-25-meta-rmarkdown/)

**What is this?**\
**Excerpt from blog:** A meta collection of all things R
Markdown. This post will focus on 4 core strategies of why R
Markdown is SO useful and absolutely worth learning with
links to external tactics/guides/write-ups of how to
accomplish the various tasks.

1.  Link to blog here:
    <https://themockup.blog/posts/2020-07-25-meta-rmarkdown/>
2.  Link to slides here:
    <https://docs.google.com/presentation/d/e/2PACX-1vRo1eXJtiwo6aTA8KZ2E-bUbv2GOonC2RIVk_5eWQ5y-ADXbRamBhHaa3w1vMW6BkEPOMJ13ZahSo8Q/embed?start=false&loop=true&delayms=30000&slide=id.p>
3.  Link to slides in pdf here:
    <https://github.com/jthomasmock/radix_themockup/blob/master/_posts/2020-07-25-meta-rmarkdown/rmd-slides.pdf>

## [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)💯 💯

By [Yihui Xie, Christophe Dervieux, Emily
Riederer](https://bookdown.org/yihui/rmarkdown-cookbook/)

**What is this?**

**Excerpt from ebook:** This book aims to draw together
popular posts from Stack Overflow and other online resources
(such as blog posts or tutorials) to provide up-to-date
solutions for everyday queries that users commonly make. In
fact, to help us make decisions on the potential topics to
cover in this book, the second author of this book,
Christophe, has built an R Markdown dashboard to scrape
Stack Overflow daily for the most popular posts. Hopefully,
our cookbook can become more useful by including recipes
from these popular posts.

1.  Link to ebook here:
    <https://bookdown.org/yihui/rmarkdown-cookbook/>

## [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/#)💯 💯

By [Yihui Xie, J. J. Allaire, & Garrett
Grolemund](https://bookdown.org/yihui/rmarkdown/#)

**What is this?**

**Excerpt from ebook:** Note that this book is intended to
be a guide instead of the comprehensive documentation of all
topics related to R Markdown. Some chapters are only
overviews, and you may need to consult the full
documentation elsewhere (often freely available online)

1.  Link to ebook here:
    <https://bookdown.org/yihui/rmarkdown/#>

## [R-Markdown Table generator](https://www.tablesgenerator.com/markdown_tables)

**What is this?**\
Table generator to add to R-Markdown

1.  Link to web-tool here:
    <https://www.tablesgenerator.com/markdown_tables>

## [R Markdown for Scientists](https://rmd4sci.njtierney.com/)

By [Nicholas Tierney](https://rmd4sci.njtierney.com/)

**What is this?**

**Excerpt from site:** This is a book on rmarkdown, aimed
for scientists. It was initially developed as a 3 hour
workshop, but is now developed into a resource that will
grow and change over time as a living book.

1.  Link to web-book here: <https://rmd4sci.njtierney.com/>

## [Using Word Reference Documents with RMarkdown to Create Custom Reports](https://rfortherestofus.com/2020/07/word-reference-documents-rmarkdown/)

By David Keyes

Added Thu Feb 20, 2025

**What is this?**

This tutorial demonstrates how to customize the appearance
of Word documents generated from RMarkdown by utilizing
reference documents. By creating a Word template with
desired styles and specifying it in the RMarkdown YAML
header, users can ensure consistent and personalized
formatting in their reports.

1.  Link to tutorial here:
    <https://rfortherestofus.com/2020/07/word-reference-documents-rmarkdown/>

## [Writing Reproducible Research Papers with R Markdown](https://resulumit.com/teaching/rmd_workshop#1)

By [Resul
Umit](https://resulumit.com/teaching/rmd_workshop#1)

Added Sun June 6th, 2021

**What is this?**

**Excerpt from site:** Workshop about Writing Reproducible
Research Papers with R Markdown. Two days, on how to write
reproducible research papers with R Markdown on November
2020.

200+ slides, 40+ exercises, and time for converting a real
project 1. Link to slides:
https://resulumit.com/teaching/rmd_workshop#1

1.  Link to other workshops:
    1.  [Version Control and Collaboration with Git and
        GitHub by Resul Umit on March
        2021](https://resulumit.com/teaching/git_workshop.html#1)
    2.  [Automated Web Scraping with R by Resul Umit on May
        2021](https://resulumit.com/teaching/scrp_workshop.html#1)
    3.  [Creating Academic Websites with R by Resul Umit on
        April
        2021](https://resulumit.com/teaching/rbd_workshop.html#1)
    4.  [Working with Twitter Data in R by Resul Umit on
        February
        2021](https://resulumit.com/teaching/twtr_workshop.html#1)
