---
title: "Presentation & Slides"
subtitle: "Blogs & Slides Only"
editor: 
  markdown: 
    wrap: 72
---

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/JoscelinRocha">![Buy
me a
coffee](https://cdn.buymeacoffee.com/buttons/bmc-new-btn-logo.svg){alt="Buy me a coffee"
width="15" height="21"}Buy me a coffee</a>

------------------------------------------------------------------------

## [Make your slides extra special](https://slides.garrickadenbuie.com/extra-special-xaringan/#1)💯

By [Garrick
Aden‑Buie](https://slides.garrickadenbuie.com/extra-special-xaringan/#1)

**What is this?**

Fun slides walking you through how to can make your slides made through
xaringan a little more fun!

1.  Slides link here:
    <https://slides.garrickadenbuie.com/extra-special-xaringan/#1>

## [PowerPoint presentations generation Vignettes](https://davidgohel.github.io/officer/articles/offcran/powerpoint.html)

**What is this?**\
**Excerpt from vignette:** Use the function read_pptx() to create an R
object representing a PowerPoint document. The initial PowerPoint file
can be specified with the path argument. If none is provided, this file
will be an empty document located in the package directory. Formats and
available slide layouts will be those available in the template file.
The content of original document is also preserved (but can be
manipulated, i.e. delete a slide).

1.  Link to vignette here:
    <https://davidgohel.github.io/officer/articles/offcran/powerpoint.html>

## [Sharing Your xaringan Slides](https://www.garrickadenbuie.com/blog/sharing-xaringan-slides/)

By [Garrick
Aden-Buie](https://www.garrickadenbuie.com/blog/sharing-xaringan-slides/)

**What is this?**\
**Excerpt from blog:** Showcase your presentations in style with
great-looking social media cards and responsive, seamlessly embedded
slides in web pages.

1\. Link to blog here:
<https://www.garrickadenbuie.com/blog/sharing-xaringan-slides/>

## [The Ultimate Infinite Moon Reader for xaringan Slides](https://yihui.org/en/2019/02/ultimate-inf-mr/#please-help-me-test-it)

By [Yihui
Xie](https://yihui.org/en/2019/02/ultimate-inf-mr/#please-help-me-test-it)

**What is this?**

**Excerpt from site:** Instant preview without fully rebuilding HTML,
and the linked navigation.

1.  Link to site here:
    <https://yihui.org/en/2019/02/ultimate-inf-mr/#please-help-me-test-it>

## [XaringanExtra: See slides as tiles & more](https://github.com/gadenbuie/xaringanExtra#-tile-view)

**What is this?**

if you use xaringan: install {xaringanExtra} and add this chunk to the
beginning of your slides to get this nifty tile overview! (press "o" to
see it: xaringanExtra::use)\_xaringan_extra(c("title_view")

1.  Link to package repo here:
    <https://github.com/gadenbuie/xaringanExtra>
2.  Link to see slides as tiles here:
    <https://github.com/gadenbuie/xaringanExtra#-tile-view>
3.  Link to make slides editable here:
    <https://github.com/gadenbuie/xaringanExtra#-editable-demo>
4.  Link to add a share bar to slides here:
    <https://github.com/gadenbuie/xaringanExtra#-share-again-1>
5.  Link to add sound when changing slides (requested by blind R user):
    <https://github.com/gadenbuie/xaringanExtra#-slide-tone-demo>

## [xaringan Tip: Add A Logo to All of Your Slides](https://www.garrickadenbuie.com/blog/xaringan-tip-logo-all-slides/)

By [Garrick
Aden‑Buie](https://www.garrickadenbuie.com/blog/xaringan-tip-logo-all-slides/)

**What is this?**\
**Excerpt from blog:** Here's a quick tip to help solve a common
xaringan problem: adding a logo to all of your slides.

1.  Link to blog here:
    <https://www.garrickadenbuie.com/blog/xaringan-tip-logo-all-slides/>
2.  Template repo here: <https://github.com/gadenbuie/xaringan-logo>
