---
title: "R for Neuroscientists"
subtitle: "Blogs & Slides Only"
editor: 
  markdown: 
    wrap: 72
---

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/JoscelinRocha">![Buy
me a
coffee](https://cdn.buymeacoffee.com/buttons/bmc-new-btn-logo.svg){alt="Buy me a coffee"
width="15" height="21"}Buy me a coffee</a>

------------------------------------------------------------------------

# fNIRS & NIRS

# fMRi, MRI, & qMRI

## [Visualization of MRI data in R](https://www.alexejgossmann.com/MRI_viz/)

Added Sunday Dec 13th, 2020\
**What is this?**

**Description from site:** In this blog post I present some functions
which I was able to find for MRI visualization in R, and which I found
to be very useful. All functions presented below presuppose an image in
the NIfTI data format as input, and are very user-friendly.

Uses the ***oro.nifti*** package

1.  Link to blog here: <https://www.alexejgossmann.com/MRI_viz/>
2.  Same blog difference place:
    <https://www.r-bloggers.com/2017/01/visualization-of-mri-data-in-r/>

## [Processing fMRI Data in R](https://johnmuschelli.com/Neuroimaging_in_R/fmri_proc.html#1)

By [John
Muschelli](https://johnmuschelli.com/Neuroimaging_in_R/fmri_proc.html#1)

Added Sunday Dec 13th, 2020\
**What is this?**

Slides created by John Muschelli for processing fMRI Data in R.

1.  Link to slides here:
    <https://johnmuschelli.com/Neuroimaging_in_R/fmri_proc.html#1>
2.  Link to repo here:
    <https://github.com/muschellij2/Neuroimaging_in_R>

# EEG

# All Neuro

## [neuropointillist](http://ibic.github.io/neuropointillist/)

Added Sunday Dec 13th, 2020\
**What is this?**

Description from site: Flexible modeling of neuroimaging data in R,
point by point

1.  Link to site: http://ibic.github.io/neuropointillist/
2.  Content:

-   [Simple fMRI
    example](http://ibic.github.io/neuropointillist/fmri.example.html)
-   [Advanced fMRI
    example](http://ibic.github.io/neuropointillist/fingerfootlips.example.html)
-   [Permutation testing fMRI
    example](http://ibic.github.io/neuropointillist/fingerfootlips_permute.html)
-   [Flournoy example
    (longitudinal)](http://ibic.github.io/neuropointillist/flournoy.example.html)
-   [Correcting for multiple
    comparisons](http://ibic.github.io/neuropointillist/clustercorrection.html)

## [Neuroimaging Analysis within R](https://johnmuschelli.com/imaging_in_r/)

Added Sunday Dec 13th, 2020\
**What is this?**

Series of slides with code for course on Neuroimaging Analysis: All the
PDF slides are located in a zip file here.

-   Introduction and R
    [Slides](https://johnmuschelli.com/imaging_in_r/intro/index.html),
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/intro/index.pdf), [R
    Code](https://johnmuschelli.com/imaging_in_r/intro/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/intro/index.Rmd)
-   General R (not covered at ENAR)
    [Slides](https://johnmuschelli.com/imaging_in_r/general_r/index.html),
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/general_r/index.pdf),
    [R Code](https://johnmuschelli.com/imaging_in_r/general_r/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/general_r/index.Rmd)
-   Imaging Packages in R
    [Slides](https://johnmuschelli.com/imaging_in_r/imaging_r_packages/index.html)
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/imaging_r_packages/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/imaging_r_packages/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/imaging_r_packages/index.Rmd)
-   Visualization of Images
    [Slides](https://johnmuschelli.com/imaging_in_r/visualization/index.html)
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/visualization/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/visualization/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/visualization/index.Rmd)
-   Inhomogeneity Correction
    [Slides](https://johnmuschelli.com/imaging_in_r/inhomogeneity_correction_ms/index.html),
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/inhomogeneity_correction_ms/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/inhomogeneity_correction_ms/index.R)
    [Source](https://johnmuschelli.com/imaging_in_r/inhomogeneity_correction_ms/index.Rmd)
-   Brain Extraction/Segmentation
    [Slides](https://johnmuschelli.com/imaging_in_r/brain_extraction_malf/index.html),
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/brain_extraction_malf/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/brain_extraction_malf/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/brain_extraction_malf/index.Rmd)
-   Image Registration
    [Slides](https://johnmuschelli.com/imaging_in_r/coregistration/index.html)
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/coregistration/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/coregistration/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/coregistration/index.Rmd)
-   Tissue-Class Segmentation
    [Slides](https://johnmuschelli.com/imaging_in_r/segmentation/index.html)
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/segmentation/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/segmentation/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/segmentation/index.Rmd)
-   Intensity Normalization
    [Slides](https://johnmuschelli.com/imaging_in_r/intensity_normalization/index.html),
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/intensity_normalization/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/intensity_normalization/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/intensity_normalization/index.Rmd)
-   Segmentation of MS Lesions
    [Slides](https://johnmuschelli.com/imaging_in_r/ms_lesion_segmentation/index.html),
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/ms_lesion_segmentation/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/ms_lesion_segmentation/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/ms_lesion_segmentation/index.Rmd)
-   Image Harmonization
    [Slides](https://johnmuschelli.com/imaging_in_r/image_harmonization/index.html)
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/ms_lesion_segmentation/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/image_harmonization/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/image_harmonization/index.Rmd)
-   Starting with Raw (DICOM) Data (not covered)
    [Slides](https://johnmuschelli.com/imaging_in_r/starting_with_raw_data/index.html),
    [PDF
    Slides](https://johnmuschelli.com/imaging_in_r/starting_with_raw_data/index.pdf),
    [R
    Code](https://johnmuschelli.com/imaging_in_r/starting_with_raw_data/index.R),
    [Source](https://johnmuschelli.com/imaging_in_r/starting_with_raw_data/index.Rmd)

1.  Link to site here: <https://johnmuschelli.com/imaging_in_r/>
