---
title: "Making Websites & Blogs"
subtitle: "Courses & Tutorials Only"
editor: 
  markdown: 
    wrap: 72
---

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/JoscelinRocha">![Buy
me a
coffee](https://cdn.buymeacoffee.com/buttons/bmc-new-btn-logo.svg){alt="Buy me a coffee"
width="15" height="21"}Buy me a coffee</a>

------------------------------------------------------------------------

## [How to make your own website for free in under an hour](https://www.dsquintana.blog/create-an-academic-website-free-easy-2020/)

By
[Quintana](https://www.dsquintana.blog/create-an-academic-website-free-easy-2020/)
💯

**What is this?**\
**Excerpt from blog:** This tutorial will walk you through how to make
your own website for free using the blogdown package in RStudio.

1.  Link to blog here(2019):
    https://www.dsquintana.blog/free-website-in-r-easy/
2.  Updated blog here (2020):
    https://www.dsquintana.blog/create-an-academic-website-free-easy-2020/
3.  Link to video here: https://www.youtube.com/watch?v=ox_Ue9yzf-0

## [How to build your personal academic website using opensource software](https://osf.io/jdv4n/)

By [Lena V. Kremin](https://osf.io/jdv4n/) 💯

**What is this?**\
**Excerpt from site:** By following this workshop, you will go through
the first steps of setting up your own academic website. Your finished
website will contain your biography, photo, CV, contact information, and
recent publications.

1.  Link to materials here: https://osf.io/jdv4n/

## [PrettyDoc Package](https://prettydoc.statr.me/)

Added Fri Oct 8th 2021\
**What is this?**\
**Excerpt from site:** The prettydoc package provides an alternative
engine, html_pretty, to knit your R Markdown document into pretty HTML
pages. Its usage is extremely easy: simply replace the
rmarkdown::html_document or rmarkdown::html_vignette output engine by
prettydoc::html_pretty in your R Markdown header, and use one of the
built-in themes and syntax highlighters.

1.  Link to site here: https://prettydoc.statr.me/
