---
title: "Meta-Analyses & Systematic Reviews"
subtitle: "Courses & Tutorials Only"
editor: 
  markdown: 
    wrap: 72
---

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/JoscelinRocha">![Buy
me a
coffee](https://cdn.buymeacoffee.com/buttons/bmc-new-btn-logo.svg){alt="Buy me a coffee"
width="15" height="21"}Buy me a coffee</a>

------------------------------------------------------------------------

## [Workshop: A Practical Guide for Meta-Analyses in R](https://constantinyvesplessen.com/post/workshop_meta_analysis/)

By [Constantin Yves
Plessen](https://constantinyvesplessen.com/post/workshop_meta_analysis/)

**What is this?**

**Excerpt from site:** This blogpost is an adaption from my 90 minute
workshop on all basic steps in conducting a meta-analysis in R. The
audience of the original workshop were graduate psychology students at
the University of Vienna with a focus on research methods. Most
statistical and methodical elements were already discussed, yet the
implementation in R was new to all of them. And programming in general
was new to most of them. I therefore introduced R very shortly, before
explaining the actual meta-analytical analyses more briefly. I added
some explanations and references to make the file more self-explanatory
for independent study. Therefore, this post also contains materials and
references on how to install R, R Studio, and some basic concepts of
programming.

1.  Post here:
    https://constantinyvesplessen.com/post/workshop_meta_analysis/
2.  Dataset and code here: https://osf.io/y9d2w/

## [R Code for Meta-Analysis Books](https://github.com/wviechtb/meta_analysis_books)

By [Wolfgang
Viechtbauer](https://github.com/wviechtb/meta_analysis_books)

**What is this?**

**Excerpt from repo:** This repo contains R code to reproduce the
examples and illustrations from various books on meta-analysis.

The code is provided as R Markdown documents, which are rendered to HTML
files. You can download the repo and open up the HTML files with your
browser. Or you can look at the files online here: 1. Link to repo:
https://github.com/wviechtb/meta_analysis_books

1.  Link to r code corresponding to "Practical Meta-Analysis by Lipsey
    and Wilson (2001)":
    https://wviechtb.github.io/meta_analysis_books/lipsey2001.html
2.  Link to r code corresponding to "Introduction to Meta-Analysis by
    Borenstein et al. (2009)":
    https://wviechtb.github.io/meta_analysis_books/borenstein2009.html
3.  Link to r code corresponding to "The Handbook of Research Synthesis
    and Meta-Analysis by Cooper et al. (2019)":
    https://wviechtb.github.io/meta_analysis_books/cooper2019.html
4.  Link to r code corresponding to "Publication Bias in Meta-Analysis
    by Rothstein et al. (2005)":
    https://wviechtb.github.io/meta_analysis_books/rothstein2005.html
