---
title: "R Markdown"
subtitle: "Courses & Tutorials Only"
editor: 
  markdown: 
    wrap: 60
---

<link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet"><a class="bmc-button" target="_blank" href="https://www.buymeacoffee.com/JoscelinRocha">![Buy
me a
coffee](https://cdn.buymeacoffee.com/buttons/bmc-new-btn-logo.svg){alt="Buy me a coffee"
width="15" height="21"}Buy me a coffee</a>

------------------------------------------------------------

## [Extending R Markdown](https://meghan.rbind.io/talk/rstudio/)

By [Meghan Hall](https://meghan.rbind.io/talk/rstudio/)

Added Sat Dec, 11, 2021\
**What is it?**\
**Excerpt from site:** "R Markdown is a powerful yet
underutilized tool for a powerful yet underutilized
component of data science---communicating your work. R
Markdown works seamlessly with other analytic work in R and
knowing the basics allows you to extend that knowledge into
producing PDFs, slides, websites, and more".

1.  Link to blog here:
    <https://meghan.rbind.io/talk/rstudio/>
2.  Link to slides here:
    <https://meghan.rbind.io/slides/RStudio/Hall_RStudio_2021.html#1>
3.  Link to video here:
    <https://community.rstudio.com/t/recording-of-r-in-sports-analytics-rstudio-enterprise-community-meetup/107551>
4.  Link to Github repo and code:
    <https://github.com/meghall06/personal-website/blob/master/static/slides/RStudio/Hall_RStudio_2021.Rmd>

## [R-Markdown Table generator](https://www.tablesgenerator.com/markdown_tables)

**What is this?**\
Table generator to add to R-Markdown

1.  Link to web-tool here:
    <https://www.tablesgenerator.com/markdown_tables>

## [Writing Reproducible Research Papers with R Markdown](https://resulumit.com/teaching/rmd_workshop#1)

By [Resul
Umit](https://resulumit.com/teaching/rmd_workshop#1)

Added Sun June 6th, 2021

**What is this?**

**Excerpt from site:** Workshop about Writing Reproducible
Research Papers with R Markdown. Two days, on how to write
reproducible research papers with R Markdown on November
2020.

200+ slides, 40+ exercises, and time for converting a real
project 1. Link to slides:
https://resulumit.com/teaching/rmd_workshop#1

1.  Link to other workshops:
    1.  [Version Control and Collaboration with Git and
        GitHub by Resul Umit on March
        2021](https://resulumit.com/teaching/git_workshop.html#1)
    2.  [Automated Web Scraping with R by Resul Umit on May
        2021](https://resulumit.com/teaching/scrp_workshop.html#1)
    3.  [Creating Academic Websites with R by Resul Umit on
        April
        2021](https://resulumit.com/teaching/rbd_workshop.html#1)
    4.  [Working with Twitter Data in R by Resul Umit on
        February
        2021](https://resulumit.com/teaching/twtr_workshop.html#1)
